version: '3'

services: 
    api:
        build: 
            context: .
            dockerfile: ./Dockerfile
        environment: 
            - DJANGO_DEBUG=True
            - DJANGO_DB_HOST=db
            - DJANGO_DB_PORT=3306
            - DJANGO_DB_USERNAME=admin
            - DJANGO_DB_PASSWORD=password
            - DJANGO_DB_NAME=moving
        command: >
            bash -c "./wait-for-it.sh db:3306 -t 15
            && python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/usr/src/MarketDesign_Project/
        ports: 
            - "8000:8000"
        depends_on: 
            - db

    
    db:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'admin'
            MYSQL_DATABASE: 'moving'
            MYSQL_PASSWORD: 'password'
            MYSQL_HOST: 'db'
        volumes: 
            - ./data:/docker-entrypoint-initdb.d
        ports: 
            - "3306:3306"
        expose: 
            - "3306"
